version: '3.9'

services:
  jupiter-usdc-price-alert:
    image: nicxx2/jupiter-usdc-price-alerts:latest
    container_name: jupiter-usdc-price-alerts
    restart: unless-stopped

    ports:
      # Access the Web UI at http://localhost:8000
      - "8000:8000"

    environment:
      # --- TOKEN CONFIGURATION ---
      # Fixed: USDC mint address
      INPUT_MINT: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v

      # Replace with the token you want to monitor
      OUTPUT_MINT: <YOUR_OUTPUT_TOKEN_MINT>

      # --- SIMULATED SWAP AMOUNT ---
      # Amount of USDC to simulate each check
      USD_AMOUNT: 100

      # --- CHECK INTERVAL ---
      # How often to check prices (in seconds)
      CHECK_INTERVAL: 60

      # --- ALERT THRESHOLDS ---
      # Trigger alerts if price falls below these values
      BUY_ALERTS: "0.00135,0.00130"

      # Trigger alerts if price rises above these values
      SELL_ALERTS: "0.00145,0.00150"

      # --- PUSH NOTIFICATIONS ---
      # The topic name for ntfy notifications
      NTFY_TOPIC: token-alerts

      # Default ntfy server (250 messages/day/IP)
      NTFY_SERVER: https://ntfy.sh

      # --- COOLDOWN SETTINGS ---
      # 0 = fire once per target; set minutes to allow repeats
      ALERT_RESET_MINUTES: 0

      # --- LOCAL TIMEZONE ---
      # Update to match your timezone
      TZ: Europe/London

      # --- DISCORD BOT TOKEN ---
      # Add your Discord bot token here for alert notifications
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}

    logging:
      driver: "json-file"
      options:
        # Limit individual log files to 2MB
        max-size: "2m"
        # Keep 5 rotated log files (10MB total max)
        max-file: "5"
